"""update tables

Revision ID: 572bfb86a6de
Revises: 9cc07ba05d8d
Create Date: 2023-10-25 12:20:26.077834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572bfb86a6de'
down_revision = '9cc07ba05d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_customers_delivery_address_addresses', type_='foreignkey')
        batch_op.drop_constraint('fk_customers_billing_address_addresses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customers_shipping_address_id_addresses'), 'addresses', ['shipping_address_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_customers_billing_address_id_addresses'), 'addresses', ['billing_address_id'], ['id'])
        batch_op.drop_column('billing_address')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_customers_billing_address_id_addresses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_customers_shipping_address_id_addresses'), type_='foreignkey')
        batch_op.create_foreign_key('fk_customers_billing_address_addresses', 'addresses', ['billing_address'], ['id'])
        batch_op.create_foreign_key('fk_customers_delivery_address_addresses', 'addresses', ['delivery_address'], ['id'])
        batch_op.drop_column('shipping_address_id')
        batch_op.drop_column('billing_address_id')

    # ### end Alembic commands ###
